# Generated by Django 3.2.8 on 2023-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='grower',
            name='marker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
