# Generated by Django 3.2.8 on 2023-10-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grower_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='marker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
