# Generated by Django 3.2.8 on 2023-10-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_farm_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='geom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='marker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
