# Generated by Django 3.2.8 on 2024-01-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240101_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='grower',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.RemoveConstraint(
            model_name='organization',
            name='organization_unique_if_not_deleted',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='field',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='farm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
