# Generated by Django 3.2.8 on 2023-11-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardsoilrxelements',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
