# Generated by Django 3.2.8 on 2023-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0004_alter_standardsoilrxelements_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationelement',
            name='inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
