# Generated by Django 3.2.8 on 2023-11-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0006_equationelement_output_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equationcrops',
            options={'ordering': ['crop__display_name']},
        ),
        migrations.AlterModelOptions(
            name='equationelement',
            options={'ordering': ['element__order']},
        ),
        migrations.AlterModelOptions(
            name='equationsets',
            options={'ordering': ['name']},
        ),
    ]
