# Generated by Django 3.2.8 on 2023-11-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0008_equationsets_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationelement',
            name='output_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
