# Generated by Django 3.2.8 on 2023-11-23 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0009_alter_equationelement_output_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationcrops',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equation_crop', to='equations.equationsets'),
        ),
        migrations.AlterField(
            model_name='equationelement',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equation_element', to='equations.equationcrops'),
        ),
    ]
