# Generated by Django 3.2.8 on 2023-11-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0011_auto_20231123_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equationcrops',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='equationcrops',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='equationelement',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='equationelement',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='equationsets',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='equationsets',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='standardrxcrops',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='standardrxcrops',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='standardsoilrxelements',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='standardsoilrxelements',
            name='is_deleted',
        ),
    ]
