# Generated by Django 3.2.8 on 2023-11-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0014_auto_20231129_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equationcrops',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='equationcrops',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='equationelement',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='equationelement',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='equationsets',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='equationsets',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='standardrxcrops',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='standardrxcrops',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='standardsoilrxelements',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='standardsoilrxelements',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='equationcrops',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equationcrops',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='equationelement',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equationelement',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='equationsets',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equationsets',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='standardrxcrops',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='standardrxcrops',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='standardsoilrxelements',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='standardsoilrxelements',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
