# Generated by Django 3.2.8 on 2023-10-15 20:22

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20231013_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleEvent',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('S', 'Soil'), ('T', 'Tissue'), ('N', 'Nematode')], default='S', max_length=1)),
                ('number_samples', models.IntegerField(default=0)),
                ('has_results', models.BooleanField(default=False)),
                ('has_rx', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoilSampleDepthList',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_depth', models.FloatField(blank=True, null=True)),
                ('end_depth', models.FloatField(blank=True, null=True)),
                ('column_depth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SamplesSoil',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_depth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.soilsampledepthlist')),
                ('sample_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sampleevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='depths',
            field=models.ManyToManyField(related_name='sample_event_depths', to='samples.SoilSampleDepthList'),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.field'),
        ),
    ]
