# Generated by Django 3.2.8 on 2023-10-17 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20231013_0153'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleevent',
            name='organization',
            field=models.ForeignKey(default='4fc9995b-f578-41ab-bedc-c7b85793f394', on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
            preserve_default=False,
        ),
    ]
