# Generated by Django 3.2.8 on 2023-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sampleevent_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleevent',
            name='depths',
            field=models.ManyToManyField(blank=True, null=True, related_name='sample_event_depths', to='samples.SoilSampleDepthList'),
        ),
    ]
