# Generated by Django 3.2.8 on 2023-10-26 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sampleevent_depths'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSoilDepth',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardSoilElements',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardSoilExtractions',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='samplessoil',
            name='sample_depth',
        ),
        migrations.CreateModel(
            name='SoilExtraction',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('std_related', models.ManyToManyField(blank=True, null=True, related_name='std_soil_extractions', to='samples.StandardSoilExtractions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoilElement',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('std_related', models.ManyToManyField(blank=True, null=True, related_name='std_soil_elements', to='samples.StandardSoilElements')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleSoilResults',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('value_description', models.CharField(blank=True, choices=[('VL', 'Very Low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2, null=True)),
                ('depth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.samplesoildepth')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.soilelement')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.soilextraction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='samplesoildepth',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.samplessoil'),
        ),
        migrations.AddField(
            model_name='samplesoildepth',
            name='sample_depth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.soilsampledepthlist'),
        ),
    ]
