# Generated by Django 3.2.8 on 2023-10-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20231026_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesoildepth',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depths', to='samples.samplessoil'),
        ),
    ]
