# Generated by Django 3.2.8 on 2023-10-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_samplesoildepth_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplessoil',
            name='sample_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_soil', to='samples.sampleevent'),
        ),
    ]
