# Generated by Django 3.2.8 on 2023-11-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_auto_20231103_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilextraction',
            name='soil_element',
            field=models.ForeignKey(default='ff59ef05-3f32-422b-b2ef-ef28d87d4e8c', on_delete=django.db.models.deletion.CASCADE, to='samples.soilelement'),
            preserve_default=False,
        ),
    ]
