# Generated by Django 3.2.8 on 2023-11-03 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_soilextraction_soil_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardsoilextractions',
            name='soil_std_element',
            field=models.ForeignKey(default='fa193c23-d457-4b16-9193-bfc1252e56a7', on_delete=django.db.models.deletion.CASCADE, to='samples.standardsoilelements'),
            preserve_default=False,
        ),
    ]
