# Generated by Django 3.2.8 on 2023-11-05 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_standardsoilextractions_soil_std_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilelement',
            name='units',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['lbs/ac'], size=None),
            preserve_default=False,
        ),
    ]
