# Generated by Django 3.2.8 on 2023-11-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_remove_samplesoilresults_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesoilresults',
            name='depth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_results', to='samples.samplesoildepth'),
        ),
        migrations.AlterField(
            model_name='samplesoilresults',
            name='value_description',
            field=models.CharField(blank=True, choices=[('VL', 'Very Low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default=None, max_length=2, null=True),
        ),
    ]
