# Generated by Django 3.2.8 on 2024-01-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_auto_20231115_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleevent',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sampleevent',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='samplesoildepth',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='samplesoildepth',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='samplesoilresults',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='samplesoilresults',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='samplessoil',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='samplessoil',
            name='is_deleted',
        ),
    ]
