# Generated by Django 3.2.8 on 2024-01-13 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_auto_20240101_1949'),
        ('samples', '0014_auto_20240110_1306'),
        ('equations', '0018_alter_standardsoilrxelements_default_rate_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('equation_detials', models.JSONField()),
                ('stats', models.JSONField()),
                ('geojson', models.FileField(upload_to='rx/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('equation_crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equations.equationcrops')),
                ('equation_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equations.equationsets')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('sample_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.sampleevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
