# Generated by Django 3.2.8 on 2024-01-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240101_1949'),
        ('equations', '0018_alter_standardsoilrxelements_default_rate_unit'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rxevent',
            name='equation_elements',
            field=models.ManyToManyField(to='equations.StandardSoilRxElements'),
        ),
        migrations.AddField(
            model_name='rxevent',
            name='field',
            field=models.ForeignKey(default='991aad8f-8291-49b8-bb1c-0752a24b1253', on_delete=django.db.models.deletion.CASCADE, to='core.field'),
            preserve_default=False,
        ),
    ]
