# Generated by Django 3.2.8 on 2024-01-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0018_alter_standardsoilrxelements_default_rate_unit'),
        ('recommendations', '0002_auto_20240114_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rxevent',
            name='equation_crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equations.standardrxcrops'),
        ),
    ]
