# Generated by Django 3.2.8 on 2023-12-02 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20231013_0153'),
        ('equations', '0016_auto_20231129_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardProducts',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='StandardProductElements',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_rx_element', to='equations.standardsoilrxelements')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_product_element', to='products.standardproducts')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountProducts',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('S', 'Solid'), ('L', 'Liquid')], default='S', max_length=1)),
                ('application_unit', models.CharField(max_length=20)),
                ('bulk_unit', models.CharField(max_length=20)),
                ('density', models.FloatField(blank=True, null=True)),
                ('density_unit', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AccountProductElements',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rx_element', to='equations.standardsoilrxelements')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_element', to='products.accountproducts')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
