# Generated by Django 3.2.8 on 2023-12-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountproducts',
            name='density_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
