# Generated by Django 3.2.8 on 2023-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_accountproducts_density_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproducts',
            name='bulk_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountproducts',
            name='bulk_density_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
