# Generated by Django 3.2.8 on 2023-12-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231202_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproducts',
            name='product_elements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AccountProductElements',
        ),
    ]
