# Generated by Django 3.2.8 on 2023-12-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20231013_0153'),
        ('equations', '0016_auto_20231129_0325'),
        ('products', '0005_auto_20231207_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountProductsDefults',
            new_name='AccountProductsDefaults',
        ),
    ]
